// Generated by https://quicktype.io

export interface Comments {
  message: string;
  code: number;
  data: Data;
}

export interface Data {
  total: number;
  comments: Comment[];
}

export interface Comment {
  id: number;
  writer: Writer;
  content: string;
  createdAt: string;
  replies: Reply[];
  totalReply: number;
}

export interface Reply {
  writer: Writer;
  id: number;
  parentId: number;
  content: string;
  createdAt: string;
}

export interface Writer {
  id: number;
  name: string;
  title: string;
  image: string;
}

export interface CommentsRequest {
  insightId: number;
}
