// Generated by https://quicktype.io

export interface BlockResponse {
  message: string;
  code: number;
  data: Data;
}

export interface Data {
  blockedUsers: BlockedUser[];
}

export interface BlockedUser {
  id: number;
  nickname: string;
  title: string;
  imageURL: string;
}
