// Generated by https://quicktype.io

export interface FollowersFollowings {
  message: string;
  code: number;
  data: FollowDatas;
}

export interface FollowDatas {
  nextCursor: string;
  invitees: User[];
}

export interface User {
  userId: number;
  nickname: string;
  imageURL: string;
}
