// Generated by https://quicktype.io

interface Notification {
  message: string;
  code: number;
  data: Data;
}

interface CheckNotification {
  message: string;
  code: number;
  data: { exist: boolean };
}

interface Data {
  nextCursor: number;
  notifications: NotificationElement[];
}

interface NotificationElement {
  id: number;
  title: string;
  contents: string;
  category: string;
  referenceId: string;
  read: boolean;
  createdAt: string;
}
