// Generated by https://quicktype.io

export interface Notification {
  message: string;
  code: number;
  data: Data;
}

export interface Data {
  nextCursor: number;
  notifications: NotificationElement[];
}

export interface NotificationElement {
  id: number;
  title: string;
  contents: string;
  category: string;
  referenceId: string;
  read: boolean;
}
