// Generated by https://quicktype.io

export interface HomeInsight {
  message: string;
  code: number;
  data: Datum[];
}

export interface Datum {
  id: number;
  contents: string;
  link: Link;
  reaction: Reaction;
}

export interface Link {
  url: string;
}

export interface Reaction {
  clap: number;
  heart: number;
  sad: number;
  surprise: number;
  fire: number;
  eyes: number;
}
