// Generated by https://quicktype.io

export interface Title {
  message: string;
  code: number;
  data: Datum[];
}

export interface Datum {
  titleId: number;
  name: string;
  introduction: string;
  achievedDate: string;
}
