// Generated by https://quicktype.io

import { titleMetaArr } from '../../constants/title/titleData';

export interface Title {
  message: string;
  code: number;
  data: Data;
}

export interface Data {
  repTitleId: number | null;
  achievedTitles: AchievedTitle[];
}

export interface AchievedTitle {
  titleId: number;
  name: string;
  introduction: string;
  achievedDate: string;
}

export interface TitleMeta {
  id: number;
  category: string;
  category_kor: string;
  name: string;
  introduction: string;
  url: any;
}
