// Generated by https://quicktype.io

export interface FeedInsight {
  message: string;
  code: number;
  data: InsightData[];
}

export interface InsightData {
  id: number;
  contents: string;
  createdAt: string;
  link: Link;
  reaction: Reaction;
  bookmark: boolean;
  writer: InsightWriter;
}

interface Link {
  url: string;
}

interface Reaction {
  clap: number;
  heart: number;
  sad: number;
  surprise: number;
  fire: number;
  eyes: number;
}

interface InsightWriter {
  writerId: number;
  nickname: string;
  title: string;
  image: string;
}
