name: Expo Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Eas CLI
      run: npm install -g eas-cli

    - name: Install dependencies
      run: npm install

    - name: Eas login
      run: |
        eas login 
        ${{ secrets.EXPO_USERNAME }} 
        ${{ secrets.EXPO_PASSWORD }}

    - name: Eas update
      run: eas update
